[package]
name = "house-daemon"
version = "0.1.0"
authors = ["Priit Laes <plaes@plaes.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
main_error = "0.1.1"
rumqttc = "0.5.0"
tokio = { version = "1", features = ["full"] }
